2018-06-07 16:17:12,872 - all - INFO - views.py line:104-- timestamp : 1528359432464 
2018-06-07 16:17:18,750 - all - INFO - views.py line:104-- timestamp : 1528359438702 
2018-06-07 16:17:38,490 - all - INFO - views.py line:104-- timestamp : 1528359458181 
2018-06-07 16:42:15,089 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 16:42:16,389 - all - INFO - views.py line:104-- timestamp : 1528360936379 
2018-06-07 16:42:17,279 - all - INFO - views.py line:104-- timestamp : 1528360936972 
2018-06-07 16:42:17,530 - all - INFO - views.py line:104-- timestamp : 1528360937501 
2018-06-07 16:42:17,807 - all - INFO - views.py line:104-- timestamp : 1528360937676 
2018-06-07 16:42:17,984 - all - INFO - views.py line:104-- timestamp : 1528360937869 
2018-06-07 16:42:18,175 - all - INFO - views.py line:104-- timestamp : 1528360938077 
2018-06-07 16:42:18,385 - all - INFO - views.py line:104-- timestamp : 1528360938301 
2018-06-07 16:42:19,316 - all - INFO - views.py line:104-- timestamp : 1528360939311 
2018-06-07 16:42:19,828 - all - INFO - views.py line:104-- timestamp : 1528360939710 
2018-06-07 16:42:25,826 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 16:43:18,536 - all - INFO - views.py line:104-- timestamp : 1528360998223 
2018-06-07 16:48:12,902 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 16:49:57,219 - all - INFO - views.py line:104-- timestamp : 1528361396841 
2018-06-07 16:50:06,766 - all - INFO - views.py line:104-- timestamp : 1528361406685 
2018-06-07 16:51:48,405 - all - INFO - views.py line:104-- timestamp : 1528361508093 
2018-06-07 16:51:48,786 - all - INFO - views.py line:104-- timestamp : 1528361508780 
2018-06-07 16:51:49,570 - all - INFO - views.py line:104-- timestamp : 1528361509262 
2018-06-07 16:53:14,757 - all - INFO - views.py line:104-- timestamp : 1528361594391 
2018-06-07 16:54:10,892 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 16:54:14,509 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 17:02:34,716 - all - INFO - views.py line:104-- timestamp : 1528362154401 
2018-06-07 17:08:41,206 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 17:08:46,153 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
2018-06-07 17:09:12,946 - django.request - ERROR - exception.py line:118-- Internal Server Error: /login/create_code_img/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\login\views.py", line 104, in verify_code
    logger.info("timestamp : "+request.GET.get('timestamp'))
TypeError: must be str, not NoneType
