2018-08-09 20:44:36,651 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:44:38,404 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:46:58,682 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:47:00,431 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:47:22,508 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:47:24,339 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:49:58,420 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:50:00,110 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:50:44,878 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 201, in upload
    f2 = json.loads(request.body).get("execontent")
  File "E:\common\Python\lib\site-packages\django\http\request.py", line 255, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
2018-08-09 20:52:06,932 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:52:08,501 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:52:14,005 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 201, in upload
    f2 = json.loads(request.body).get("execontent")
  File "E:\common\Python\lib\site-packages\django\http\request.py", line 255, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
2018-08-09 20:52:29,420 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:52:31,094 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:52:35,204 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 202, in upload
    print(request.body)
  File "E:\common\Python\lib\site-packages\django\http\request.py", line 255, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
2018-08-09 20:56:13,796 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:56:15,525 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:56:22,983 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 209, in upload
    wb = xlrd.open_workbook(filename=None, file_contents=f.read())  # 关键点在于这里
NameError: name 'f' is not defined
2018-08-09 20:56:45,148 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:56:46,939 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 20:57:05,464 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 20:57:07,161 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:42:51,810 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:42:54,037 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:43:35,139 - all - INFO - views.py line:119-- timestamp : 1533822215037 
2018-08-09 21:44:27,247 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:44:29,174 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:45:19,439 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:45:21,321 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:45:29,983 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:45:31,682 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:47:26,406 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:47:28,274 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:48:01,331 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:48:03,130 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:48:06,200 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:48:06,774 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:48:10,668 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:48:11,400 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:54:17,357 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:54:19,140 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:54:33,732 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:54:39,213 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:54:41,945 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 206, in upload
    print(myform.cleaned_data["execontent"].name)
AttributeError: 'str' object has no attribute 'name'
2018-08-09 21:55:04,067 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:55:05,722 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:56:25,324 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:56:27,108 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:56:36,140 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:56:37,908 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 21:59:58,036 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 21:59:59,707 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 22:01:03,529 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 22:01:05,154 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 22:01:10,859 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 223, in upload
    value = {"user_id": user_id, "excel_name": request.FILES.get('file',None).name, "is_push_check": is_push_check, "notice_content": myform.cleaned_data["execontent"],
NameError: name 'user_id' is not defined
2018-08-09 22:01:56,188 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-10 13:07:04,194 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
